# Generated by Django 4.0.2 on 2022-02-22 17:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_data_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='patient_name',
            field=models.TextField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
